In [43]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]
x = data.iloc[:,:-1]
y= data.iloc[:,-1]
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [23]:
from sklearn import linear_model
clf = linear_model.SGDClassifier(eta0=0.001, alpha=0.001, loss='log',random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf.fit(X=x, y=y)
clf.coef_

-- Epoch 1
Norm: 10.78, NNZs: 3, Bias: -0.017500, T: 200, Avg. loss: 25162.588749
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 6.13, NNZs: 3, Bias: -0.015500, T: 400, Avg. loss: 26216.210376
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 3.49, NNZs: 3, Bias: -0.018500, T: 600, Avg. loss: 32851.729308
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 7.92, NNZs: 3, Bias: -0.027500, T: 800, Avg. loss: 30789.148650
Total training time: 0.01 seconds.
-- Epoch 5
Norm: 8.76, NNZs: 3, Bias: -0.032500, T: 1000, Avg. loss: 30015.982607
Total training time: 0.01 seconds.
-- Epoch 6
Norm: 9.92, NNZs: 3, Bias: -0.024500, T: 1200, Avg. loss: 29690.931055
Total training time: 0.01 seconds.
Convergence after 6 epochs took 0.01 seconds


array([[ 4.1639715 , -8.91579066,  1.28733856]])

Observation:
1. Considering the features are not multicollinear, we can directly use absolute value of weights and decide upon the most important features. If there is collinearity then we have to use other techniques like forward feature selection.
2. Feature importance order: F2>F1>F3 according to weights.

In [25]:
clf = linear_model.SGDClassifier(eta0=0.001, alpha=0.001, loss='hinge', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf.fit(X=x, y=y)
clf.coef_

-- Epoch 1
Norm: 6.11, NNZs: 3, Bias: -0.016000, T: 200, Avg. loss: 26336.457910
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 6.75, NNZs: 3, Bias: -0.011000, T: 400, Avg. loss: 25927.053650
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 7.56, NNZs: 3, Bias: -0.009000, T: 600, Avg. loss: 33077.171384
Total training time: 0.01 seconds.
-- Epoch 4
Norm: 7.69, NNZs: 3, Bias: -0.027000, T: 800, Avg. loss: 31546.551215
Total training time: 0.01 seconds.
-- Epoch 5
Norm: 9.30, NNZs: 3, Bias: -0.028000, T: 1000, Avg. loss: 30800.517488
Total training time: 0.01 seconds.
-- Epoch 6
Norm: 4.27, NNZs: 3, Bias: -0.027000, T: 1200, Avg. loss: 30114.441106
Total training time: 0.01 seconds.
-- Epoch 7
Norm: 6.93, NNZs: 3, Bias: -0.022000, T: 1400, Avg. loss: 30016.955979
Total training time: 0.01 seconds.
Convergence after 7 epochs took 0.01 seconds


array([[ 3.81782233, -5.57723074,  1.53976662]])

Observation:
1. Considering the features are not multicollinear, we can directly use the absolute value of weights and decide upon the most important features. If there is collinearity then we have to use other techniques like forward feature selection.
2. Feature importance order: F2>F1>F3 according to weights.

In [42]:
col1 = np.array(data.iloc[:,0])
col2 = np.array(data.iloc[:,1])
col3 = np.array(data.iloc[:,2])
for i in range(len(col1)):
    col1[i] = (col1[i]-col1.mean())/col1.std()
    col2[i] = (col2[i]-col2.mean())/col2.std()
    col3[i] = (col3[i]-col3.mean())/col3.std()
data1 = {'f1':col1,'f2':col2,'f3':col3}
df = pd.DataFrame(data1)
clf = linear_model.SGDClassifier(eta0=0.001, alpha=0.001, loss='log', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf.fit(X=df, y=y)
clf.coef_


-- Epoch 1
Norm: 0.08, NNZs: 3, Bias: -0.001770, T: 200, Avg. loss: 0.677171
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.16, NNZs: 3, Bias: -0.006515, T: 400, Avg. loss: 0.646162
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.22, NNZs: 3, Bias: -0.013955, T: 600, Avg. loss: 0.621043
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.28, NNZs: 3, Bias: -0.023568, T: 800, Avg. loss: 0.600506
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.34, NNZs: 3, Bias: -0.034991, T: 1000, Avg. loss: 0.583303
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.39, NNZs: 3, Bias: -0.047705, T: 1200, Avg. loss: 0.568775
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.44, NNZs: 3, Bias: -0.061532, T: 1400, Avg. loss: 0.556074
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.48, NNZs: 3, Bias: -0.076227, T: 1600, Avg. loss: 0.544991
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.52, NNZs: 3, Bias: -0.091307, T: 1800, Avg. loss: 0.535102
Total training time: 0

array([[-0.19809769, -0.1842337 ,  1.36427005]])

Observations:
1. Considering the features are not multicollinear, we can directly use absolute value of weights and decide upon the most important features. If there is collinearity then we have to use other techniques like forward feature selection.
2. Feature importance order: F3>F1>F2 according to weights. We can see the same pattern in correlation also. F3 is strongly correlated than other features.  More weight is given to F3. Then F1 is strongly coorelated as compared to F2. More weight is given to F1 than F2.

In [46]:
clf = linear_model.SGDClassifier(eta0=0.001, alpha=0.001, loss='hinge', random_state=15, penalty='l2', tol=1e-3, verbose=2, learning_rate='constant')
clf.fit(X=df, y=y)
clf.coef_

-- Epoch 1
Norm: 0.18, NNZs: 3, Bias: 0.000000, T: 200, Avg. loss: 0.930971
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 0.34, NNZs: 3, Bias: -0.002000, T: 400, Avg. loss: 0.782287
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 0.45, NNZs: 3, Bias: -0.024000, T: 600, Avg. loss: 0.681001
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 0.53, NNZs: 3, Bias: -0.057000, T: 800, Avg. loss: 0.631480
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 0.60, NNZs: 3, Bias: -0.095000, T: 1000, Avg. loss: 0.594566
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 0.66, NNZs: 3, Bias: -0.133000, T: 1200, Avg. loss: 0.566353
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 0.71, NNZs: 3, Bias: -0.173000, T: 1400, Avg. loss: 0.542882
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 0.75, NNZs: 3, Bias: -0.214000, T: 1600, Avg. loss: 0.524276
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 0.79, NNZs: 3, Bias: -0.256000, T: 1800, Avg. loss: 0.506512
Total training time: 0.

array([[-0.168297  , -0.1116561 ,  1.28187845]])

Observations:
1. Feature importance order: F3>F1>F2 according to weights. We can see the same pattern in correlation also. F3 is strongly correlated than other features. More weight is given to F3. Then F1 is strongly correlated as compared to F2. More weight is given to F1 than F2.